//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// 注册信息类
/// </summary>
public class clsRegInfo
{
	/// <summary>
	/// 授权到期期限
	/// </summary>
	public virtual Long TimeTo
	{
		get;
		set;
	}

	/// <summary>
	/// 是否为代理商使用
	/// </summary>
	public virtual bool IsToProxy
	{
		get;
		set;
	}

	/// <summary>
	/// 机器ID
	/// </summary>
	public virtual string ID
	{
		get;
		set;
	}

}

