//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// 加密解密类
/// </summary>
public class EncryptDecrypt
{
	/// <summary>
	/// 获得CUPID
	/// </summary>
	private static string GetCPUID()
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 获取主板ID
	/// </summary>
	private static string GetMotherBoardID()
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 获取网卡ID
	/// </summary>
	private static string GetMacID()
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 获得本机ID
	/// </summary>
	public static string GetID()
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// MD5加密
	/// </summary>
	/// <param name="pToEncrypt">需要加密的字符串</param>
	public static void MD5(string pToEncrypt)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// DES加密
	/// </summary>
	/// <param name="pToEncrypt">需要加密的字符串</param>
	/// <param name="pKey">密匙，长度为8</param>
	public static string DESEncrypt(string pToEncrypt, string pKey)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// DES解密
	/// </summary>
	/// <param name="pToDecrypt">需要DES解密的字符串</param>
	/// <param name="pKey">DES密匙</param>
	public static void DESDecrypt(string pToDecrypt, string pKey)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 生成注册文件
	/// </summary>
	/// <param name="reginfo">注册信息</param>
	/// <param name="path">导出路径</param>
	public static bool GetRegFile(clsRegInfo reginfo, string path)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 读取注册文件
	/// </summary>
	/// <param name="path">文件路径</param>
	public static bool LoadRegFile(string path)
	{
		throw new System.NotImplementedException();
	}

}

